### PR TITLE
correction du paquet envoyé et de la réponse attendue pour permettre …

### PR DESCRIPTION
**Pull request by jgaret**
…le démarrage du RFXTRX433E avec firmware plus récent

### CODE REVIEW

**Comment by fritz-smh** [comment]
This way it will not work with the other rfxcom model.
I will add some other changes to make it work with both models.

The PR is usefull for me to get the good informations, I will close it when the fix will be ok

**Comment by jgaret** [comment]
I am not sure it's a model problem. I guess it's more related to firmware version. But it needs testing to be sure.

**Comment by fritz-smh** [comment]
Can you try with the last push on develop ?
I didn't check for the 20 length but for the 14 length which was the diff I found in the logs you give me by email.

Why did you use 20 on your side ?

Notice : I will try to get a recent documentation about rfxcom sdk as we are currently doing only some hypothesis

**Comment by fritz-smh** [comment]
Additionnal information : in a february 2016 SDK, I found that the waited message can be a length of 0x14 or 0x0D
I will wait for your feedback before doing new updates.

I also requested the last SDK to Rfxcom.

**Comment by jgaret** [comment]
It works from develop. rfxcom plugin starts and gets the packets.

**Comment by fritz-smh** [comment]
This is a good news :)

**Comment by jgaret** [comment]
Integrated with commit https://github.com/fritz-smh/domogik-plugin-rfxcom/commit/b2a23d9926bd0c48b72021bf69f65ddf3c5d4201 I am closing this PR, now useless.

**Pull request closed without merging**
